apiVersion: "v1"
kind: "Service"
metadata:
  name: "grafana-service"
  namespace: "default"
  labels:
    {{ .Values.label_key }}: {{ .Values.label_value }}
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    {{ .Values.label_key }}: {{ .Values.label_value }}