version: 2.1
jobs:
 build:
   machine: true
   environment:
     GRAFANA_VERSION: 7.2.2
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: cd image && docker build --build-arg GRAFANA_VERSION=$GRAFANA_VERSION -t levkov/grafana:$GRAFANA_VERSION .
     - run: cd image && docker push levkov/grafana:$GRAFANA_VERSION