version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  helm: circleci/helm@1.0.1
  aws-cli: circleci/aws-cli@1.3.0
jobs:
 build:
   machine: true
   environment:
     GRAFANA_VERSION: 7.2.2
   steps:
     - checkout
     - kubernetes/install-kubectl
     - aws-cli/install
     - helm/install-helm-client: 
         version: v3.0.0
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: cd image && docker build --build-arg GRAFANA_VERSION=$GRAFANA_VERSION -t levkov/grafana:$GRAFANA_VERSION .
     - run: cd image && docker push levkov/grafana:$GRAFANA_VERSION
     - run: aws version