apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - host: grafana.minikube.levkov.net
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-service
          servicePort: 80